run:
  timeout: 5m
  tests: false
linters:
  enable-all: true
  disable:
    - cyclop
    - wsl
    - godox
    - gochecknoglobals
    - ireturn
    - nlreturn
    - testpackage
    - paralleltest
    - exhaustruct
    - gocognit
    - gochecknoinits
    - gocyclo
    - funlen
    - maintidx
    - musttag
    - wrapcheck
linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - "github.com/gatewayd-io/gatewayd/api/v1"
          - "github.com/gatewayd-io/gatewayd-plugin-sdk"
          - "github.com/gatewayd-io/gatewayd-plugin-cache"
          - "github.com/prometheus/client_golang"
          - "github.com/hashicorp/go-plugin"
          - "github.com/hashicorp/go-hclog"
          - "github.com/go-redis/redis/v8"
          - "github.com/getsentry/sentry-go"
          - "github.com/spf13/cast"
          - "github.com/go-co-op/gocron"
