name: Build and release gatewayd-plugin-cache

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          cache: true
      - run: |
          git config --global url."https://mostafa:${TOKEN}@github.com/".insteadOf "https://github.com"
          go mod tidy
        env:
          TOKEN: ${{ secrets.GH_SDK_TOKEN }}
          GOPRIVATE: github.com/gatewayd-io/gatewayd-*
      - name: Build and release binaries
        run: make build-release-linux
      - name: Create release and add artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
            dist/checksums.txt
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
  build-and-release-darwin:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          cache: true
      - run: |
          go mod tidy
        env:
          GOPRIVATE: github.com/gatewayd-io/gatewayd-*
      - name: Build and release binaries
        run: make build-release-darwin
      - name: Create release and add artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
            dist/checksums.txt
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
  build-and-release-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          cache: true
      - run: |
          go mod tidy
        env:
          GOPRIVATE: github.com/gatewayd-io/gatewayd-*
      - name: Build and release binaries
        run: make build-release-windows
      - name: Create release and add artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.zip
            dist/checksums.txt
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
